[env:promicro]
platform = atmelavr
board = leonardo  ; Pro Micro uses same chip as Leonardo (ATmega32u4)
framework = arduino

; Serial Monitor settings
monitor_speed = 115200
monitor_filters = direct

; Library dependencies
lib_deps = 
    ; Wire@^1.0
    ; Weitere Libraries hier hinzufügen
    ; SPI@^1.0
    ; Adafruit Unified Sensor@^1.1.4

; Upload settings
upload_speed = 115200

; Build flags (optional)
build_flags = 
    -DDEBUG=1